# version of docker compose
version: "3.8"

services:
  smart-brain-api:
    container_name: backend

    # use the image from docker hub
    # image: node:8.11.1

    # build the image by the Dockerfile
    build: ./

    # run the command when starting run this service
    command: npm run start:dev
    # command: >
    #   bash -c "npm install
    #   && npm run start:dev"

    working_dir: /usr/src/smart-brain-api
    environment:
      POSTGRES_URI: postgres://howard:secret@postgres:5432/smart-brain-docker
      REDIS_URI: redis://redis:6379

    # do not need links; it will connect automatically
    # links:
    #   - postgres
    #   - redis

    ports:
      - "3000:3000"

    volumes: # mount local machine to docker container
      - ./:/usr/src/smart-brain-api

  # Postgres
  postgres:
    # no need container_name if using image
    # container_name: database

    # environment variable
    environment:
      POSTGRES_USER: howard
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres

    # no need image bacause there is build
    # image: postgres

    build: ./postgres

    ports:
      - "5432:5432"

# Redis
  redis:
    image: redis
  
    ports:
      - "6379:6379"