BEGIN TRANSACTION;

CREATE TABLE users (
  id serial PRIMARY KEY,
  email text UNIQUE NOT NULL,
  entries BIGINT DEFAULT 0,
  joined TIMESTAMP NOT NULL,
  name VARCHAR(100),
  age INT,
  pet VARCHAR(100)
);

COMMIT; 